import React, { useState } from "react";

function StudentView({ onBack }) {
  const [selectedTab, setSelectedTab] = useState("overview"); // overview | assignments | recommendations

  const [assignmentDone, setAssignmentDone] = useState(false);

  return (
    <div className="page">
      <button onClick={onBack}>← Back</button>

      <h1>Student view</h1>
      <p>
        This screen shows how a student would experience EduAssist: clear
        assignments, simple progress, and AI-powered guidance.
      </p>

      {/* Tabs for the student */}
      <div style={{ display: "flex", gap: "0.5rem", marginTop: "1.2rem" }}>
        <button
          onClick={() => setSelectedTab("overview")}
          style={{
            background: selectedTab === "overview" ? "#16a34a" : "#e5e7eb",
            color: selectedTab === "overview" ? "white" : "black",
          }}
        >
          Overview
        </button>
        <button
          onClick={() => setSelectedTab("assignments")}
          style={{
            background: selectedTab === "assignments" ? "#16a34a" : "#e5e7eb",
            color: selectedTab === "assignments" ? "white" : "black",
          }}
        >
          My assignments
        </button>
        <button
          onClick={() => setSelectedTab("recommendations")}
          style={{
            background: selectedTab === "recommendations" ? "#16a34a" : "#e5e7eb",
            color: selectedTab === "recommendations" ? "white" : "black",
          }}
        >
          My AI tips
        </button>
      </div>

      {/* CONTENT: Overview */}
      {selectedTab === "overview" && (
        <div className="card">
          <h2>Welcome to EduAssist</h2>
          <p>
            Here the student can see a simple summary of what they need to do
            and how they are progressing. The goal is to reduce anxiety and make
            the next step very clear.
          </p>
          <ul style={{ marginTop: "0.75rem" }}>
            <li>• 1 assignment due this week.</li>
            <li>• AI suggests focusing on fractions and reading comprehension.</li>
            <li>• Progress: 3 of 4 assignments completed.</li>
          </ul>
        </div>
      )}

      {/* CONTENT: Assignments */}
      {selectedTab === "assignments" && (
        <div className="card">
          <h2>My current assignment</h2>
          <p style={{ fontSize: "0.9rem", color: "#555" }}>
            Example of how a student would see an assignment generated by AI
            from a teacher&apos;s document.
          </p>

          <div style={{ marginTop: "0.9rem" }}>
            <h3>“Reading task – Main ideas”</h3>
            <ol style={{ marginTop: "0.5rem" }}>
              <li>Read the short text provided by your teacher.</li>
              <li>Write a 5–7 sentence summary in your own words.</li>
              <li>Highlight three key ideas and explain why they matter.</li>
              <li>Write two questions you still have after reading.</li>
            </ol>

            <p className="ai-text" style={{ marginTop: "0.6rem" }}>
              ✨ This assignment was created automatically from your teacher&apos;s
              document using AI.
            </p>

            <button
              style={{ marginTop: "0.8rem" }}
              onClick={() => setAssignmentDone(true)}
            >
              Mark as done
            </button>

            {assignmentDone && (
              <p className="success">
                ✅ Great job! This assignment is now marked as completed.
              </p>
            )}
          </div>
        </div>
      )}

      {/* CONTENT: AI tips for the student */}
      {selectedTab === "recommendations" && (
        <div className="card">
          <h2>My AI tips</h2>
          <p className="ai-text">
            Here is how AI could talk directly to the student, giving simple,
            supportive guidance based on their learning style.
          </p>

          <div className="ai-recommendations" style={{ marginTop: "0.9rem" }}>
            <div className="ai-recommendations-header">
              <div>
                <span className="ai-pill">AI coach</span>
                <h3>Personal learning tips</h3>
                <p className="ai-text">
                  Based on your recent activity, EduAssist suggests:
                </p>
              </div>
              <div className="ai-icon">🤖</div>
            </div>

            <ul className="ai-recommendations-list">
              <li>
                <div className="ai-bullet">✓</div>
                <div className="ai-recommendation-content">
                  <div className="ai-recommendation-title">
                    Start with short sessions
                  </div>
                  <div className="ai-recommendation-body">
                    Try studying in <b>10–15 minute blocks</b> with small breaks.
                    This makes it easier to stay focused and reduces stress.
                  </div>
                  <span className="ai-tag">Focus</span>
                </div>
              </li>

              <li>
                <div className="ai-bullet">✓</div>
                <div className="ai-recommendation-content">
                  <div className="ai-recommendation-title">
                    Use visual supports
                  </div>
                  <div className="ai-recommendation-body">
                    Draw a simple diagram or mind map after you read something.
                    It helps your brain organize information visually.
                  </div>
                  <span className="ai-tag">Visual learning</span>
                </div>
              </li>

              <li>
                <div className="ai-bullet">✓</div>
                <div className="ai-recommendation-content">
                  <div className="ai-recommendation-title">
                    Ask your own questions
                  </div>
                  <div className="ai-recommendation-body">
                    After each lesson, write down one question you still have.
                    This helps you stay curious and remember more.
                  </div>
                  <span className="ai-tag">Metacognition</span>
                </div>
              </li>

              <li>
                <div className="ai-bullet">✓</div>
                <div className="ai-recommendation-content">
                  <div className="ai-recommendation-title">
                    Celebrate small wins
                  </div>
                  <div className="ai-recommendation-body">
                    When you finish a task, take a second to notice it. Small
                    wins matter, especially if learning sometimes feels
                    overwhelming.
                  </div>
                  <span className="ai-tag">Wellbeing</span>
                </div>
              </li>
            </ul>

            <p className="ai-text ai-footer">
              ✨ In the full version, these tips would adapt dynamically as the
              student interacts with the platform.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}

export default StudentView;